/**********************************************************************************************************************
 * \file cy_base_hdmi.c
 * \copyright Copyright (C) Infineon Technologies AG 2025
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cybsp.h"
#include "cygfx_defines.h"
#include "cygfx_basetypes.h"
#include "cy_fpdlink.h"
#include "cy_gfx_env.h"
#include "cmsis_compiler.h"

#include "cy_lvds_hdmi.h"
#include <stdio.h>
#include "platform_irq.h"

/*******************************************************************************
* Macros
********************************************************************************/ 

#define SYSTICK_RELOAD_VAL   (10000000UL)
#define SYSTICK_PERIOD_TIMES (10u)
#define PD_BASE                                 0x40B00000UL
#define PD_CTL_PWR_MODE_Msk                     0x3UL
#define PD_STATUS_PWR_DONE_Msk                  0x10UL
#define VIDEOSS0_BASE                           0x40A00000UL

/* Select the display */
#define WAVESHARE_800_480_5INCH         0
#define SELECT_EMBEDDED_DISPLAY         WAVESHARE_800_480_5INCH
#define DISP1_TYPE                      CY_GFXENV_DISP_TYPE_800_480_60_HDMI_VESA
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
cy_stc_hdmi_trx_config_t hdmiLvdsConfig =
{
    .colorBits      = CY_LVDS_LINK_8BIT,
    .encodeFormat   = CY_LVDS_FORMAT_VESA,
    .colorFormat    = CY_HDMI_COLOR_RGB444,
    .singleOrDual   = CY_LVDS_LINK_SINGLE,
    .videoType      = CY_HDMI_800x480w60,
};

/* VideoSS interrupts configurations */

static const cy_gfxenv_stc_cfg_t m_stcGfxEnvCfg =
{
    .bInitSwTimer         = true,
    .bInitSemihosting     = true,
    .pstcInitPortPins     = &(cy_gfxenv_stc_init_portpins_t)
                            {
                              #if (CY_USE_PSVP == 0)
                                .bInitDisplay0Ttl       = false, /* usually the FPD-Link is used on silicon */
                              #else
                                .bInitDisplay0Ttl       = true,  /* FPD-Link #0 is not available on PSVP */
                              #endif
                              #if (CY_USE_PSVP == 0) && defined(VIDEOSS0_FPDLINK1)
                                .bInitDisplay1Ttl       = false, /* usually the FPD-Link is used on silicon (if it is available) */
                              #else
                                .bInitDisplay1Ttl       = true,  /* FPD-Link #1 is not available on PSVP or on silicon for this device */
                              #endif
                                .bInitCapture0Ttl       = false,
                                .bInitSmif0             = false,
                                .bInitSmif1             = false,
                                .bInitBacklightDisp0    = false, /* backlights are enabled by jumper setting on CY boards, would only be needed for PWM dimming */
                                .bInitBacklightDisp1    = false, /* backlights are enabled by jumper setting on CY boards, would only be needed for PWM dimming */
                                .bInitBacklightFpdLink0 = false, /* backlights are enabled by jumper setting on CY boards, would only be needed for PWM dimming */
                                .bInitBacklightFpdLink1 = false, /* backlights are enabled by jumper setting on CY boards, would only be needed for PWM dimming */
                                .bInitButtonGpios       = false,
                            },
    .pstcInitExtMem       = NULL,
    .pstcInitButtons      = &(cy_gfxenv_stc_init_buttons_t)
                            {
                                .u8CySwTimerId = (CY_SWTMR_MAX_TIMERS - 1), /* use last timer */
                                .pfnCallback = NULL,
                            }
};


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
extern void GfxDrvExampleInit(CYGFX_U32 res_x, CYGFX_U32 res_y);
extern void GfxDrvExampleDraw(void);
extern cy_en_hdmi_trx_status_t Cy_IT6263_HDMI_SetVideoOutput(void);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This main achieve the systick timer interrupt function. Toggle user led when generate
 *  the systick interrupt up to 10 times.
 *
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{

    cy_rslt_t bsp_result;

    /* Initialize the device and board peripherals */
    bsp_result = cybsp_init();
    if (bsp_result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    
    __enable_irq();

    /* Enable Graphics Subsystem Power Switch */
    Cy_PD_Enable(); 
    Cy_GfxEnv_Init(&m_stcGfxEnvCfg);
    SCB_DisableICache();
    SCB_DisableDCache();
    Cy_SysLib_Delay(250);
    SCB_EnableDCache();
    SCB_EnableICache();    

    ConfigureVideoSSInterrupt();
    /* Initialize the HDMI transceiver */
    Cy_HDMI_Transceiver_Init(hdmiLvdsConfig);

    Cy_GfxEnv_EnableHdmiTestImage(DISP1_TYPE); /* CY_GFXENV_DISP_TYPE_800_480_60_HDMI_VESA */

    cy_en_hdmi_trx_status_t HDMI_TX_Ret;
    for(uint8_t i=0; i<8; i++)
    {
        HDMI_TX_Ret = Cy_HDMI_Transceiver_DeviceLoop();
        while(HDMI_TX_Ret != CY_HDMI_TRX_SUCCESS)
        {
            break;
        }
    }
    if(HDMI_TX_Ret != CY_HDMI_TRX_SUCCESS)
    {
        printf("Failed.--------------------------- \n\r");
    }

    for(;;)
    {
        /* Check for HDMI event for hotplug in */
        Cy_HDMI_Transceiver_DeviceLoop();
        Cy_GPIO_Inv(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);

    }
}
/* [] END OF FILE */
