/**********************************************************************************************************************
 * \file platform_irq.c
 * \copyright Copyright (C) Infineon Technologies AG 2025
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/* Copyright (C) 2024 The Qt Company Ltd.
 SPDX-License-Identifier: LicenseRef-Qt-Commercial */
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "platform_irq.h"

#ifdef __GNUC__
#include "cybsp.h"
#include "cy_gfx_env.h"
#include "cy_retarget_io.h"

/* VideoSS Interrupts Config */
const cy_stc_sysint_t irq_cfg[]
    = {{.intrSrc = ((NvicMux3_IRQn << CY_SYSINT_INTRSRC_MUXIRQ_SHIFT) | videoss_0_interrupt_gfx2d_IRQn),
        .intrPriority = 3},
       {.intrSrc = ((NvicMux3_IRQn << CY_SYSINT_INTRSRC_MUXIRQ_SHIFT) | videoss_0_interrupt_videoio0_IRQn),
        .intrPriority = 3},
       {.intrSrc = ((NvicMux3_IRQn << CY_SYSINT_INTRSRC_MUXIRQ_SHIFT) | videoss_0_interrupt_videoio1_IRQn),
        .intrPriority = 3}};

extern void CyGfx_kInterruptHandlerVideoio0(void);
extern void CyGfx_kInterruptHandlerVideoio1(void);
extern void CyGfx_kInterruptHandlerGfx2d(void);

static void SDL_VideoSSInterruptHandler(void)
{ /* Call VIDEOSS Interrupt handlers */
    CyGfx_kInterruptHandlerVideoio0();
    CyGfx_kInterruptHandlerVideoio1();
    CyGfx_kInterruptHandlerGfx2d();

    /* Clear Interrupt flag */
    NVIC_ClearPendingIRQ((IRQn_Type) NvicMux3_IRQn);
}

void ConfigureVideoSSInterrupt()
{
    /* Initialize VideoSS interrupts */
    Cy_SysInt_Init(&irq_cfg[0], (cy_israddress) SDL_VideoSSInterruptHandler); //GFX_2D
    Cy_SysInt_Init(&irq_cfg[1], (cy_israddress) SDL_VideoSSInterruptHandler); //VideoIO0
    Cy_SysInt_Init(&irq_cfg[2], (cy_israddress) SDL_VideoSSInterruptHandler); //VideoIO1

    /* Set Prio/Enable IRQ */
    NVIC_ClearPendingIRQ((IRQn_Type) NvicMux3_IRQn);
    NVIC_EnableIRQ((IRQn_Type) NvicMux3_IRQn);
}
#else
#include "cy_project.h"
#include "cy_device_headers.h"
#include "cygfx_driver_api.h"
#include "ut_compatibility.h"
#include "ut_memman.h"
#include "cy_gfx_env.h"

/* VideoSS Interrupts Config */
static const cy_stc_sysint_irq_t irq_cfg[] = {{//VIDEOSS_0_INTERRUPT_GFX2D_HANDLER
                                               .sysIntSrc = videoss_0_interrupt_gfx2d_IRQn, //150
                                               .intIdx = CPUIntIdx3_IRQn,
                                               .isEnabled = true},
                                              {//VIDEOSS_0_INTERRUPT_VIDEOIO0_HANDLER
                                               .sysIntSrc = videoss_0_interrupt_videoio0_IRQn, //152
                                               .intIdx = CPUIntIdx3_IRQn,
                                               .isEnabled = true},
                                              {//VIDEOSS_0_INTERRUPT_VIDEOIO1_HANDLER
                                               .sysIntSrc = videoss_0_interrupt_videoio1_IRQn, //153
                                               .intIdx = CPUIntIdx3_IRQn,
                                               .isEnabled = true}};

/* VideoSS Interrupts Handler */
static void SDL_VideoSSInterruptHandler(void)
{
    /* Call VIDEOSS Interrupt handlers */
    CyGfx_kInterruptHandlerVideoio0();
    CyGfx_kInterruptHandlerVideoio1();
    CyGfx_kInterruptHandlerGfx2d();

    /* Clear Interrupt flag */
    NVIC_ClearPendingIRQ(CPUIntIdx3_IRQn);
}

void ConfigureVideoSSInterrupt()
{
    /* Initialize VideoSS interrupts */
    Cy_SysInt_InitIRQ(&irq_cfg[0]); //GFX_2D
    Cy_SysInt_InitIRQ(&irq_cfg[1]); //VideoIO0
    Cy_SysInt_InitIRQ(&irq_cfg[2]); //VideoIO1

    /* Set Handlers */
    Cy_SysInt_SetSystemIrqVector(irq_cfg[0].sysIntSrc, SDL_VideoSSInterruptHandler);
    Cy_SysInt_SetSystemIrqVector(irq_cfg[1].sysIntSrc, SDL_VideoSSInterruptHandler);
    Cy_SysInt_SetSystemIrqVector(irq_cfg[2].sysIntSrc, SDL_VideoSSInterruptHandler);

    /* Set Prio/Enable IRQ */
    NVIC_SetPriority(CPUIntIdx3_IRQn, 3);
    NVIC_ClearPendingIRQ(CPUIntIdx3_IRQn);
    NVIC_EnableIRQ(CPUIntIdx3_IRQn);
}
#endif
