/**********************************************************************************************************************
 * \file cy_i2c_hdmi.c
 * \copyright Copyright (C) Infineon Technologies AG 2025
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "cy_device_headers.h"
#include "cy_i2c_hdmi.h"
#include "cy_it6263_config.h"
#include "cybsp.h"
#include "cy_pdl.h"
#include "cy_retarget_io.h"
#include "mtb_hal.h"
#include "cy_gfx_env.h"

/* I2C port configuration macro */
static cy_stc_gpio_pin_config_t hdmi_i2c_port_pin_cfg =
{
    .outVal   = 0x00,
    .intEdge  = 0,
    .intMask  = 0,
    .vtrip    = 0,
    .slewRate = 0,
    .driveSel = 0,
    .vregEn   = 0,
    .ibufMode = 0,
    .vtripSel = 0,
    .vrefSel  = 0,
    .vohSel   = 0,
};

/* I2C irq configuration macro */
static cy_stc_sysint_t hdmi_i2c_irq_cfg =
{
    .intrSrc = ((NvicMux2_IRQn << CY_SYSINT_INTRSRC_MUXIRQ_SHIFT) | scb_1_interrupt_IRQn),
    .intrPriority = 3
};

/* I2C master configuration macro */
static cy_stc_scb_i2c_config_t hdmi_i2c_stc_config =
{
    .i2cMode             = CY_SCB_I2C_MASTER,
    .useRxFifo           = true,
    .useTxFifo           = true,
    .acceptAddrInFifo    = false,
    .ackGeneralAddr      = false,
    .enableWakeFromSleep = false
};

/* I2C master configuration structure */
static cy_stc_scb_i2c_master_xfer_config_t hdmi_i2c_stc_master_config =
{
    .buffer       = 0,
    .bufferSize   = 0,
    .xferPending  = false
};


/* Sensor interface I2C contex */
static cy_stc_scb_i2c_context_t hdmi_i2c_stc_context;


/* Image Sensor local function definition */
static void Cy_IT6263_I2C_IntrISR (void);
static void Cy_IT6263_I2C_SetPeripheFracDiv24_5(uint64_t targetFreq, uint64_t sourceFreq, uint8_t divNum);
static void Cy_IT6263_I2C_MasterEvent(uint32_t locEvents);

/*******************************************************************************
* Function Name: Cy_IT6263_I2C_IntrISR
****************************************************************************//**
*
* \brief
* LVDS to HDMI transceiver i2c interrupt callback.
*
* \param  none
*
* \return none
*
*******************************************************************************/
static void Cy_IT6263_I2C_IntrISR(void)
{
    /* I2C interrupt handler for High-Level APIs */
    Cy_SCB_I2C_Interrupt(CY_FPD_HDMI_I2C_TYPE, &hdmi_i2c_stc_context);
}

/*******************************************************************************
* Function Name: Cy_IT6263_I2C_SetPeripheFracDiv24_5
****************************************************************************//**
*
* \brief
* LVDS to HDMI transceiver i2c set up clock fractional divider.
*
* \param
* targetFreq : frequency for i2c operation
*
* \param
* sourceFreq : frequency for scb block
* 
* \param
* divNum : divider no used for the target frequency
*
* \return none
*
*******************************************************************************/
static void Cy_IT6263_I2C_SetPeripheFracDiv24_5(uint64_t targetFreq, uint64_t sourceFreq, uint8_t divNum)
{
    uint64_t temp = ((uint64_t)sourceFreq << 5ull);
    uint32_t divSetting;

    divSetting = (uint32_t)(temp / targetFreq);
    /* Need to migrate it to PDL??? */
    Cy_SysClk_PeriphSetFracDivider(/*Cy_SysTick_GetClockSource(CY_FPD_HDMI_I2C_PCLK),*/ 
    								/*Cy_SysTick_GetClockSource(),*/
                                   CY_SYSCLK_DIV_24_5_BIT, divNum, 
                                   (((divSetting >> 5u) & 0x00000FFF) - 1u), 
                                   (divSetting & 0x0000001F));
}

/*******************************************************************************
* Function Name: Cy_IT6263_I2C_MasterEvent
****************************************************************************//**
*
* \brief
* LVDS to HDMI transceiver i2c event callback.
*
* \param
* locEvents : i2c block generated event id
*
* \return none
*
*******************************************************************************/
static void Cy_IT6263_I2C_MasterEvent(uint32_t locEvents)
{
    switch (locEvents)
    {
    case CY_SCB_I2C_MASTER_WR_IN_FIFO_EVENT:
        break;
    case CY_SCB_I2C_MASTER_WR_CMPLT_EVENT:
        break;
    case CY_SCB_I2C_MASTER_RD_CMPLT_EVENT:
        break;
    case CY_SCB_I2C_MASTER_ERR_EVENT:
        break;
    default:
        break;
    }
}

/*******************************************************************************
* Function Name: Cy_IT6263_I2C_Init
****************************************************************************//**
*
* \brief
* Function to initialize i2c control path for LVDS to HDMI transceiver.
*
* \param  none
*
* \return
* cy_en_i2c_result_t : function result type
*
* \note
* SCB1 is fixed for the LVDS to HDMI transceiver control path.
* 
*******************************************************************************/
cy_en_i2c_result_t Cy_IT6263_I2C_Init(void)
{
    cy_en_i2c_result_t status = CY_I2C_SUCCESS;
    

    /* Clock Configuration */
    Cy_SysClk_ClkHfEnable(CY_CFG_SYSCLK_CLKHF2);

    Cy_SysClk_ClkHfGetFrequency(2);  
    Cy_SysClk_PllGetFrequency(7);  

    /* CY_FPD_HDMI_I2C_PCLK - PCLK_SCB1_CLOCK */
    Cy_SysClk_PeriphAssignDivider(CY_FPD_HDMI_I2C_PCLK, CY_SYSCLK_DIV_24_5_BIT, CY_HDMI_I2C_DIVIDER_NO);
    Cy_IT6263_I2C_SetPeripheFracDiv24_5(CY_HDMI_I2C_INCLK_TARGET_FREQ, CY_HDMI_I2C_SOURCE_CLK_FREQ, CY_HDMI_I2C_DIVIDER_NO);
    Cy_SysClk_PeriphEnableDivider(CY_SYSCLK_DIV_24_5_BIT, CY_HDMI_I2C_DIVIDER_NO);

    Cy_SysClk_ClkHfGetFrequency(2);  
    Cy_SysClk_PllGetFrequency(7);  

    /* Port Configuration */
    hdmi_i2c_port_pin_cfg.driveMode = CY_GPIO_DM_OD_DRIVESLOW;
    hdmi_i2c_port_pin_cfg.hsiom     = CY_FPD_HDMI_I2C_SDA_PIN_MUX;
    Cy_GPIO_Pin_Init(CY_FPD_HDMI_I2C_SDA_PORT, CY_FPD_HDMI_I2C_SDA_PIN, &hdmi_i2c_port_pin_cfg);

    hdmi_i2c_port_pin_cfg.driveMode = CY_GPIO_DM_OD_DRIVESLOW;
    hdmi_i2c_port_pin_cfg.hsiom     = CY_FPD_HDMI_I2C_SCL_PIN_MUX;
    Cy_GPIO_Pin_Init(CY_FPD_HDMI_I2C_SCL_PORT, CY_FPD_HDMI_I2C_SCL_PIN, &hdmi_i2c_port_pin_cfg);

    /* Interrupt Configuration */
    Cy_SysInt_Init(&hdmi_i2c_irq_cfg,Cy_IT6263_I2C_IntrISR);
    NVIC_ClearPendingIRQ((IRQn_Type)hdmi_i2c_irq_cfg.intrSrc);
    NVIC_EnableIRQ((IRQn_Type) NvicMux2_IRQn);
    
    /*  Initilize & Enable I2C  */
    Cy_SCB_I2C_Init(CY_FPD_HDMI_I2C_TYPE, &hdmi_i2c_stc_config, &hdmi_i2c_stc_context);
    Cy_SCB_I2C_SetDataRate(CY_FPD_HDMI_I2C_TYPE, CY_HDMI_I2C_DATARATE, CY_HDMI_I2C_INCLK_TARGET_FREQ);
    Cy_SCB_I2C_RegisterEventCallback(CY_FPD_HDMI_I2C_TYPE, (cy_cb_scb_i2c_handle_events_t)Cy_IT6263_I2C_MasterEvent, &hdmi_i2c_stc_context);
    Cy_SCB_I2C_Enable(CY_FPD_HDMI_I2C_TYPE);

    return status;
}

/*******************************************************************************
* Function Name: Cy_IT6263_I2C_Read
****************************************************************************//**
*
* \brief
* Function to read register in image sensor.
*
* \param
* deviceAddr : address of the target device
*
* \param
* regAddr : register address of image sensor
*
* \return
* uint8_t : read value
*
*******************************************************************************/
uint8_t Cy_IT6263_I2C_Read(uint8_t deviceAddr, uint8_t regAddr)
{
    cy_en_i2c_result_t status = CY_I2C_SUCCESS;
    uint8_t *regadd = (uint8_t*)&regAddr;
    uint8_t buf[2];
    
    /* retry command */
    for(uint8_t cnt=0; cnt<CY_IT6263_CMD_RETRY_COUNT ; cnt++)
    {
        hdmi_i2c_stc_master_config.slaveAddress = deviceAddr;
        hdmi_i2c_stc_master_config.buffer = regadd;
        hdmi_i2c_stc_master_config.bufferSize = 1;
        status = (cy_en_i2c_result_t)Cy_SCB_I2C_MasterWrite(CY_FPD_HDMI_I2C_TYPE, &hdmi_i2c_stc_master_config, &hdmi_i2c_stc_context);
        Cy_SysLib_Delay(CY_IT6263_CMD_IN_BW_DELAY/1000);
        hdmi_i2c_stc_master_config.buffer = buf;
        hdmi_i2c_stc_master_config.bufferSize = 1;
        status = (cy_en_i2c_result_t) Cy_SCB_I2C_MasterRead(CY_FPD_HDMI_I2C_TYPE, &hdmi_i2c_stc_master_config, &hdmi_i2c_stc_context);
        Cy_SysLib_Delay(CY_IT6263_CMD_IN_BW_DELAY/1000);
        if (status == CY_I2C_SUCCESS)
        {
            break;
        }
    }
    return buf[0];
}

/*******************************************************************************
* Function Name: Cy_IT6263_I2C_Write
****************************************************************************//**
*
* \brief
* Function to write register in LVDS to HDMI transceiver.
*
* \param
* deviceAddr : address of the target device
*
* \param
* regAddr : register address of LVDS to HDMI transceiver.
*
* \param
* value : data value
*
* \return
* cy_en_i2c_result_t : function result type
*
*******************************************************************************/
cy_en_i2c_result_t Cy_IT6263_I2C_Write(uint8_t deviceAddr, uint8_t regAddr, uint8_t value)
{
    cy_en_i2c_result_t status = CY_I2C_SUCCESS;
    uint8_t dataWrite[2];

    dataWrite[0] = regAddr;
    dataWrite[1] = value;
    
    /* retry command */
    for(uint8_t cnt=0; cnt<CY_IT6263_CMD_RETRY_COUNT ; cnt++)
    {
        hdmi_i2c_stc_master_config.slaveAddress = deviceAddr;
        hdmi_i2c_stc_master_config.buffer = dataWrite;
        hdmi_i2c_stc_master_config.bufferSize = 2;
        status = (cy_en_i2c_result_t)Cy_SCB_I2C_MasterWrite(CY_FPD_HDMI_I2C_TYPE, &hdmi_i2c_stc_master_config, &hdmi_i2c_stc_context);
        Cy_SysLib_Delay(CY_IT6263_CMD_IN_BW_DELAY/1000);
        if (status == CY_I2C_SUCCESS)
        {
            break;
        }
    }
    return status;
}

/*******************************************************************************
* Function Name: Cy_IT6263_I2C_ReadWrite
****************************************************************************//**
*
* \brief
* Function to read and then write the I2C configuration.
*
* \param
* deviceAddr : address of the target device
*
* \param
* regAddr : register address of LVDS to HDMI transceiver.
*
* \param
* value : data value
*
* \param
* op : operation on read data value
*
* \return 
* cy_en_i2c_result_t : function result type
*
*******************************************************************************/
cy_en_i2c_result_t Cy_IT6263_I2C_ReadWrite(uint8_t deviceAddr, uint8_t regAddr, uint8_t value, cy_en_i2c_op_type_t op)
{
    uint8_t readValue = 0;
    cy_en_i2c_result_t status = CY_I2C_SUCCESS;
    
    /* Read the register value */
    readValue = Cy_IT6263_I2C_Read(deviceAddr, regAddr);
    
    /* Update the changes */
    if (op == CY_I2C_OP_AND)
    {
        readValue &= value;
    }
    else
    {
        readValue |= value;
    }
    
    /* Write updated value */
    Cy_IT6263_I2C_Write(deviceAddr, regAddr, readValue);
      
    return status;
}

/*******************************************************************************
* Function Name: Cy_IT6263_I2C_WriteConfigurationSettings
****************************************************************************//**
*
* \brief
* Function to write LVDS to HDMI transceiver default configuration.
*
* \param
* deviceAddr : address of the target device
*
* \param
* cy_stc_It6263_reg_t : set of register needs to be configured
*
* \param
* configSettingsSize : size of the register array
*
* \return 
* cy_en_i2c_result_t : function result type
*
*******************************************************************************/
cy_en_i2c_result_t Cy_IT6263_I2C_WriteConfigurationSettings(uint8_t deviceAddr, cy_stc_It6263_reg_t * configSettings, uint8_t configSettingsSize)
{
    uint16_t regCounter = 0;
    cy_en_i2c_result_t status = CY_I2C_SUCCESS;
    uint8_t rwBuffer;

    for (regCounter = 0; ((regCounter < configSettingsSize) && (status == CY_I2C_SUCCESS)); regCounter++)
    {
        rwBuffer = configSettings[regCounter].regValue;
        status = Cy_IT6263_I2C_Write(deviceAddr, configSettings[regCounter].regAddr, rwBuffer); 
    }

    return status;
}


/******************************************************************************/
/* [] END OF FILE */
/******************************************************************************/
